name: AutoSell
main: LamPocketVN\AutoSell\AutoSell
version: 0.2.lpk
api: [3.0.0, 4.0.0]
authors: [LamPocketVN, Adam1609]
description: Auto-Sell plugin
depend: 
- PHP-Sell
commands:
  autosell:
    description: "Sells the item in your hand or all of your inventory's contents"
    permission: autosell.command
permissions:
  autosell.command:
    default: true
